config/routes.rb
Sampleapp::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  resources :microposts, :only => [:create, :destroy]

  match '/signup', :to=>'users#new'
  match '/contact', :to=>'pages#contact'
  match '/about', :to=>'pages#about'
  match '/help', :to=>'pages#help'

  match '/signup', :to=>'users#new'
  match '/signin', :to=>'sessions#new'
  match '/signout', :to=>'sessions#destroy'

  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
# Schema version: 20110104235516
#
# Table name: users
#
#  id                 :integer(4)      not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#

require 'digest'

class User < ActiveRecord::Base
    attr_accessor :password
    attr_accessible :name, :email
    attr_accessible :password, :password_confirmation

    has_many :microposts, :dependent => :destroy

    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :name, :presence=>true,
                    :length=>{:maximum => 50}
    validates :email, :presence=>true,
                    :format=>{:with=>email_regex},
                    :uniqueness=>{:case_sensitve=>false}

    validates :password, :presence=>true,
                        :confirmation=>true,
                        :length=>{:within=>6..40}

    before_save :encrypt_password

    def has_password?(submitted_password)
       encrypted_password == encrypt(submitted_password) 
    end

    def self.authenticate(email, submitted_password)
        user = find_by_email(email)
        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end

    def self.authenticate_with_salt(id, cookie_salt)
        user = find_by_id(id)
        (user && user.salt == cookie_salt) ? user : nil
    end

    def feed
        Micropost.where("user_id = ?", id)
    end

    private
        def encrypt_password
            self.salt = make_salt if new_record?
            self.encrypted_password = encrypt(password)
        end

        def encrypt(string)
            secure_hash("#{salt}--#{string}")
        end

        def make_salt
            secure_hash("#{Time.now.utc}--#{password}")
        end

        def secure_hash(string)
            Digest::SHA2.hexdigest(string)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      @title = "Home"
      if signed_in?
        @micropost = Micropost.new if signed_in?
        @feed_items = current_user.feed.paginate(:page=>params[:page])
      end
  end

  def contact
      @title = "Contact"
  end

  def about
      @title = "About"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
      @title = "Sign In"
  end

  def create
      user = User.authenticate(params[:session][:email],
                               params[:session][:password])

      if user.nil?

          flash.now[:error] = "Invalid email/password combo"
          @title = "Sign In"
          render 'new'
      else
          sign_in user
          redirect_back_or user
      end
  end

  def destroy
      sign_out
      redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]

  def new
      @title = "Sign Up"
      @user = User.new

  end

  def create
    @user = User.new(params[:user])

    if @user.save
        sign_in @user
        flash[:success] = "Welcome to the Sample App"
        redirect_to @user
    else
        @title = "Sign up"
        render 'new'
    end
  end

  def show
      @user = User.find(params[:id])
      @microposts = @user.microposts.paginate(:page=>params[:page])
      @title = @user.name
  end

  def edit
    #@user = User.find(params[:id])
    @title = "Edit user"
  end

  def index
    @title = "All users"
  #  @users = User.all
    @users = User.paginate(:page => params[:page])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
        flash[:success] = "Profile updated"
        redirect_to @user
    else
        @title = "Edit user"
        render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end

  private
    #def authenticate
    #    deny_access unless signed_in?
    #end

    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
        redirect_to(root_path) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def title
        base_title = "Ruby on Rails Tutorial Sample App"
        if @title.nil?
            base_title
        else
            "#{base_title} | #{@title}"
        end
            
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        cookies.permanent.signed[:remember_token] = [user.id, user.salt]
        self.current_user = user
    end

    def current_user?(user)
        user == current_user
    end

    def current_user
        @current_user ||= user_from_remember_token
    end

    def current_user=(user)
        @current_user = user
    end

    def signed_in?
        !current_user.nil?
    end

    def sign_out
        cookies.delete(:remember_token)
        self.current_user = nil
    end

    def deny_access
        store_location
        redirect_to signin_path, :notice => "Please sign in to access this page"
    end

    def redirect_back_or(default)
        puts "hey whats up #{session[:return_to]}"
        redirect_to(session[:return_to] || default)
        clear_return_to
    end

    def authenticate
        deny_access unless signed_in?
    end


    private

        def store_location
            puts "hey #{request.fullpath}"
            session[:return_to] = request.fullpath
        end

        def clear_return_to
            session[:return_to] = nil
        end

        def user_from_remember_token
            User.authenticate_with_salt(*remember_token)
        end

        def remember_token
            cookies.signed[:remember_token] || [nil, nil]
        end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {:size=>50})
        gravatar_image_tag(user.email.downcase, 
                           :alt => user.name,
                           :class => "gravatar",
                           :gravatar => options)
    end
end

app/views/layouts/_footer.html.erb
<footer>
    <nav class="round">
    <ul>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    <li><%= link_to "Google", 'http://www.google.com' %></li>
    </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <% logo = image_tag("logo.png", :alt=>"Sample app", 
        :class=>"round") %>
        <%= link_to logo, root_path %>
            <nav class="round">
                <ul>
                    <li><%= link_to "Home", root_path %></li>
                    <% if signed_in? %>
                        <li><%= link_to "Profile", current_user %>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li>
                        <%= link_to "Users", users_path %>
                        </li>
                    <% end %>
                    <li><%= link_to "Help", help_path  %></li>
                    <% if signed_in? %>
                        <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
                    <% else %>
                        <li><%= link_to "Sign in", signin_path %>
                    <% end %>
                </ul>
            </nav>
            
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_tag 'blueprint/screen', :media=>'screen' %>
<%= stylesheet_tag 'blueprint/print', :media=>'print' %>
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_tag 'custom', :media=>'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>  
        <title><%= title %>
        </title>
        <%= csrf_meta_tag %>
        <%= render 'layouts/stylesheets' %>
        <%= javascript_include_tag :defaults %>
    </head>
    <body>
        <div class="container">
            <%= render 'layouts/header' %>
            <section class="round">
            <% flash.each do |key, value| %>
                <div class="flash <%= key %>"><%= value %> </div> 
            <% end %>
 
                <%= yield %>
            </section>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>

app/views/pages/about.html.erb
        <h1>Sample App</h1>
        <p> 
            This is the about page for the sample app
        </p>    

app/views/pages/contact.html.erb
        <h1>Sample App</h1>
        <p> 
        This is the contact page for the sample app
        </p>

app/views/pages/home.html.erb
<% if signed_in? %>
    <table class="front" summary="For signed-in users">
        <tr>
            <td class="main">
                <h1 class="micropost">What is up?</h1>
                <%= render 'shared/micropost_form' %>
                <%= render 'shared/feed' %>
            </td>
            <td class="sidebar round">
                <%= render 'shared/user_info' %> 
            </td>
        </tr>
    </table>
<% else %>


<h1>Sample App</h1>
<p> 
    This is the home page for the sample app
</p>    
<%= link_to "Sign up now!", signup_path, :class=>"signup_button round" %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>  
    <div id="error_explanation">
        <h2><%= pluralize(object.errors.count, "error") %>
            prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved: </h2>
        <p>There were problems with the following fields:</p>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
            <% end %>
        </ul>
    </div>  
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="field">
        <%= f.label :name %> <br/>
        <%= f.text_field :name %>
    </div>  
    <div class="field">
        <%= f.label :email %> <br/>
        <%= f.text_field :email %> <br/>
    </div>
    <div class="field">
        <%= f.label :password %> <br/>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br/>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
        <%= f.submit "Sign Up"%>
    </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
    <tr>
        <td class="main">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
            <% unless @user.microposts.empty? %>
                <table class="microposts" summary="User microposts">
                    <%= render @microposts %>
                </table>
                <%= will_paginate @microposts %>
            <% end %>
        </td>
        <td class="sidebar round">
            <strong>Name</strong> <%= @user.name %><br />
            <strong>URL</strong> 
            <%= link_to user_path(@user), @user %><br/>
            <strong>Microposts</strong><%= @user.microposts.count %>
        </td>
    </tr>
</table>